version: '3.4'

x-logging:
  &default-logging
  options:
    max-size: '256m'
    max-file: '3'
  driver: json-file
  
volumes:
  foot:
  nginx-conf-d:

services:
  spider-1:
    image: golang
    logging: *default-logging
    restart: always
    hostname: spider-1.foot
    volumes:
        - zk-1-conf:/conf
        - zk-1-data:/data 
        - zk-1-datalog:/datalog 
    environment:
      ZOO_MY_ID: 1
    network_mode: "host"

  analy-1:
    image: golang
    logging: *default-logging
    restart: always
    hostname: analy-1.foot
    volumes:
        - zk-2-conf:/conf 
        - zk-2-data:/data 
        - zk-2-datalog:/datalog
    environment:
      ZOO_MY_ID: 2
    network_mode: "host"

  wechat-1:
    image: golang
    logging: *default-logging
    restart: always
    hostname: wechat-1.foot
    volumes:
        - zk-3-conf:/conf 
        - zk-3-data:/data 
        - zk-3-datalog:/datalog
    environment:
      ZOO_MY_ID: 3
    network_mode: "host"
    
  pub-1:
    image: golang
    logging: *default-logging
    restart: always
    hostname: pub-1.foot
    volumes:
        - assembly-zk-1-conf:/conf 
        - assembly-zk-1-data:/data 
        - assembly-zk-1-datalog:/datalog
    environment:
      ZOO_MY_ID: 1
    network_mode: "host"




      


  
   