version: '3.4'

x-logging:
  &default-logging
  options:
    max-size: '256m'
    max-file: '3'
  driver: json-file
  
volumes:
  foot-data:

services:
  #单个
  near-1:
    image: tesou/base:1.0
    logging: *default-logging
    restart: always
    hostname: near-1.foot
    volumes:
      - foot-data:/usr/local/apps/foot
    network_mode: "host"
    command: bash -c "cd /usr/local/apps/foot && chmod u+x ./FOOT000 && ./FOOT000 autoNear "

  #单个
  analy-1:
    image: tesou/base:1.0
    logging: *default-logging
    restart: always
    hostname: analy-1.foot
    volumes:
      - foot-data:/usr/local/apps/foot
    environment:
      ZOO_MY_ID: 2
    network_mode: "host"
    command: bash -c "cd /usr/local/apps/foot && chmod u+x ./FOOT000 && ./FOOT000 analy auto "

  #单个
  wechat-1:
    image: tesou/base:1.0
    logging: *default-logging
    restart: always
    hostname: wechat-1.foot
    volumes:
      - foot-data:/usr/local/apps/foot
    environment:
      ZOO_MY_ID: 3
    network_mode: "host"
    command: bash -c "cd /usr/local/apps/foot && chmod u+x ./FOOT000 && ./FOOT000 mp auto "




      


  
   